### PR TITLE
Upgrade Thinking Sphinx to 3.1.4 - requires sphinx > 2.1.4

### PR DESCRIPTION
**Pull request by azul**
There we go. Finally the upgrade of thinking sphinx. :dancer: 

In order to deploy this we will need a fairly recent version of Sphinx.
I suggest we jump right to the latest of the 2.2 series. :sparkles: 

Thinking Sphinx now uses app/indices for its index definitions.
It also requires some options to search to be hashes.

:memo: There's a nice upgrade documentation that i followed:
http://freelancing-gods.com/thinking-sphinx/upgrading.html
Most of it does not affect us though.

### CODE REVIEW

**Comment by azul** [comment]
:warning: Do NOT merge this pull request before we are ready to upgrade the production sphinx version.

**Comment by elijh** [comment]
thinking_sphinx has actually always required hashes and not arrays, but before it was an "undocumented feature" that arrays would work as well.

here are the notes that are in README_GEMS:

we don't modify the code, but we depend on an undocumented
and unsupported "feature" of thinking sphinx, one that the
author has said is an unintended byproduct of the
implementation. I think it should be a feature, because it
is cool.

Here is the problem: you pass attribute filters to search() using
:with => {}. But what do you do if you want to have multiple
contraints on the same field? You are stuck, because you can't
have two keys that are the same. 

So, instead, you can pass an array. Rather than:

    Page.search 'text', :with => {:access_ids => '1 2 3'}

You can do multiple constraints on the same field by doing this:

    Page.search 'text', :with =>
     [[:access_ids, '1 2 3'], [:access_ids, '4 5 6']]

This will search "(1 OR 2 OR 3) AND (4 OR 5 OR 6)"

This might break in future versions of thinking_sphinx.

Here is the part of the code that makes it work with arrays
and not just hashes:

lib/thinking_sphinx/search.rb:

    (options[:with] || {}).collect { |attrib, value|
       Riddle::Client::Filter.new attrib.to_s, filter_value(value)
    }

**Comment by elijh** [comment]
anyway, my point is that if this still works in thinking sphinx, we should use arrays and not hashes, because there are some places that will add multiple constraints on the same key.

**Comment by elijh** [comment]
otherwise, coooool

**Comment by elijh** [comment]
also, someone has gone emoji crazy. is this coming to cg?

**Comment by azul** [comment]
[Here](http://freelancing-gods.com/thinking-sphinx/searching.html#filters)'s the new way of doing this:

> You can also perform combination AND and OR matches with :with_all using nested arrays:

```ruby
# All pancackes belonging to tag 3 and belonging to one of tag 1 or tag 2
Article.search 'pancakes',
  :with_all => {:tag_ids => [[1,2], 3]}
```

**Comment by azul** [comment]
updated the pr with the fixes mentioned above. Let's see how the build goes now.

**Comment by elijh** [comment]
nice.

**Comment by azul** [comment]
almost done. Will release 0.6.2 before this though.

**Pull request merged**
