### PR TITLE
Feature/wikiversion

### PR DESCRIPTION
**Pull request by elijh**
revert to the old behavior: don't save a new wiki version if the same user edits twice in 30 minutes.

i have no idea what removing this was supposed to fix. i restored most of the missing wiki tests, and added some more, but i haven't been able to think of anything that could break by not creating new versions for quick saves.

### CODE REVIEW

**Comment by azul** [comment]
Yay! thanks. One test still failing:

>  1) Failure:
> 
> Wikis::VersionsControllerTest#test_version_show [/home/travis/build/riseuplabs/crabgrass-
> core/extensions/pages/wiki_page/test/functional/wikis/versions_controller_test.rb:28]:
> 
> Expected response to be a <:success>, but was <302>

**Comment by elijh** [comment]
i have not been able to figure out how to get that fucking test to pass. if you have some time i would love your help. the integration tests drive me crazy: they are brittle, hard to write, and slow as shit.

**Comment by elijh** [comment]
much to my shame, i spent three hours trying to fix that test without any progress :(

**Comment by azul** [comment]
@elijh, I'm happy to look into this one.

I've run into issues with the integration tests as well. I have not found any way to make them more robust and I rely on them to avoid clicking through the whole app. I would not be as confident in not breaking stuff without them. I'll try to figure out a way to make them more robust again at some point.

**Comment by azul** [comment]
@elijh for me and travis only a functional test seems to be failing. I tried to fix it in #316.

**Comment by azul** [comment]
@elijh ahh... now i see which test you were referring to. The test fails because the underlying  behaviour changed. Multiple updates by the same user will not yield new versions anymore. I adopted the test.

**Comment by elijh** [comment]
It turns out there are deeper issues here, the way acts_as_versioned works is incompatible with choosing sometimes to not create a new version, because it sometimes leads to incorrect assignment of the author for past versions. I am investigating a fix.

**Comment by azul** [comment]
I also [noticed](https://github.com/azul/crabgrass-core/commit/fc2c6ed78d3b97034c3bd0f222f88c1656095efb#diff-1f7f598ae7c27852a7b88851ab87336bR40) this.

The version count is not incremented so the old version is overwritten with the new versions properties. I also looked into a fix but it grew quite complex. I was thinking about raising an error or validating that `wiki.body_changed?` is true. However I think the workflow would be fairly different from a failing validation. I would expect a notice, maybe a warning to show up if i save sth. i have not changed and then i would expect to move on and not stay on the form (as a failing validation does by default).

So I decided this is a different issue that is independent of this one. It was that way before already I think.

@elijh, any objections against merging #316, closing this one and then creating a new pull request for the past author overwriting if the content did not change?

**Comment by azul** [comment]
#316 superseeded this.

**Pull request closed without merging**
