### PR TITLE
Vagrant integration

### PR DESCRIPTION
**Pull request by aliaksandrb**
Hi @azul !

I dare to take the liberty to offer an automated development environment setup using Vagrant and Virtualbox.

Using this approach everybody could setup an reproducible environment isolated from the host system at resources level as well as without a necessity to pollute it with project related packages (just reinstalled Linux at my own laptop and don't want to have all the time running search engines and databases from different projects anymore :scream:).

Have tested the README steps on two machines with a basic Ubuntu installed - works fine!

For my opinion despite the fact that such approach requires a bit more powerful machine the steps are easy (specially for people who have Vagrant and Virtualbox already) and maybe will help to invite some more contributors or bring back the ones who have faced problems during installation process (actually there are some).

Another good point is that it even shipped with a Sphinx working (for development), the thing which previously I was lazy to setup :sweat_smile:.

So how do you feel about it?
I am fine if you think that it is not necessary to put this into `master`. Will use it personally then.

### CODE REVIEW

**Comment by azul** [comment]
Hi @aliaksandrb,
This looks good. I don't plan to use vagrant myself - but i'm in a special position since i use my machine to work on crabgrass most of the time. I can see how this would be useful for others. So thanks for looking into it.

I have a few comments about the pull request itself:
* The main README file should be for the big picture only. Please move the vagrant steps to a different file in doc and point people there from the README. Thanks! :memo: 
* Just recently I learned that one can have a [user gitignore file](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore). I'm planing on cleaning up the gitignore from all the things that are environment specific. For example vim creates those `.filename.swp` files. People who use vim could have this in their gitignore file and the crabgrass one would only include files that are created by crabgrass itself and thus are specific to crabgrass and affect everyone. I think the vagrant files in .gitignore would fall into the first category. What do you think about this approach? (We don't have to start with this now - just a thought :thought_balloon: ).
* there seems to be a change to the page_term fixtures included. I don't think this is related. I don't think it will have any effect as just the ids and timestamps changed. But maybe you could clean it up never the less. :recycle:

**Comment by aliaksandrb** [comment]
Cool!

I will update the `README` according to your notes.

Of course I could revert the `page_fixtures` changes but the reason is why
it was updated is the `test:update_fixtures` step, which I follow from the
`README`. So seems that we need to do it each time after initial test suite
run.

I have no strong feelings against personal `.gitignore` approach. Then the
repo ones would not grow so much, but in the same time it means that every
user should care about their environment specific temp files and it means
that the risk of including something redundant is growing, as not many
knows about this `git` feature.

So it is more the question about who takes the responsibility of
controlling such files - repo owner or user.

Anyway, I would update my settings, as might be the `Vagrant` feature would
not be popular, so there is no need to mention it as global option.

Thanks!

**Comment by aliaksandrb** [comment]
The PR was updated according to feedback provided.

**Comment by azul** [comment]
Great! Thanks a lot @aliaksandrb.

**Pull request merged**
